# python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="gaussian_noise" --severity="1" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="gaussian_noise" --severity="2" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="gaussian_noise" --severity="3" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="gaussian_noise" --severity="4" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="gaussian_noise" --severity="5" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"

python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="shot_noise" --severity="1" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="shot_noise" --severity="2" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="shot_noise" --severity="3" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="shot_noise" --severity="4" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="shot_noise" --severity="5" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"

python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="impulse_noise" --severity="1" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="impulse_noise" --severity="2" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="impulse_noise" --severity="3" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="impulse_noise" --severity="4" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="impulse_noise" --severity="5" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"

python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="defocus_blur" --severity="1" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="defocus_blur" --severity="2" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="defocus_blur" --severity="3" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="defocus_blur" --severity="4" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="defocus_blur" --severity="5" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"

python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="glass_blur" --severity="1" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="glass_blur" --severity="2" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="glass_blur" --severity="3" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="glass_blur" --severity="4" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="glass_blur" --severity="5" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"

python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="motion_blur" --severity="1" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="motion_blur" --severity="2" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="motion_blur" --severity="3" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="motion_blur" --severity="4" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="motion_blur" --severity="5" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"

python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="zoom_blur" --severity="1" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="zoom_blur" --severity="2" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="zoom_blur" --severity="3" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="zoom_blur" --severity="4" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="zoom_blur" --severity="5" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"

python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="snow" --severity="1" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="snow" --severity="2" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="snow" --severity="3" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="snow" --severity="4" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="snow" --severity="5" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"

python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="frost" --severity="1" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="frost" --severity="2" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="frost" --severity="3" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="frost" --severity="4" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="frost" --severity="5" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"

python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="fog" --severity="1" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="fog" --severity="2" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="fog" --severity="3" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="fog" --severity="4" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="fog" --severity="5" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"

python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="brightness" --severity="1" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="brightness" --severity="2" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="brightness" --severity="3" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="brightness" --severity="4" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="brightness" --severity="5" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"

python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="contrast" --severity="1" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="contrast" --severity="2" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="contrast" --severity="3" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="contrast" --severity="4" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="contrast" --severity="5" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"

python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="elastic_transform" --severity="1" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="elastic_transform" --severity="2" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="elastic_transform" --severity="3" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="elastic_transform" --severity="4" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="elastic_transform" --severity="5" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"

python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="pixelate" --severity="1" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="pixelate" --severity="2" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="pixelate" --severity="3" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="pixelate" --severity="4" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="pixelate" --severity="5" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"

python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="jpeg_compression" --severity="1" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="jpeg_compression" --severity="2" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="jpeg_compression" --severity="3" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="jpeg_compression" --severity="4" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"
python baselines/imagenet/test.py --data_dir="/root/tensorflow_datasets" --corruption_type="jpeg_compression" --severity="5" --output_dir="checkpoints/density_softmax/imagenet/model2" --use_gpu="True" --num_cores="1" --seed="1"